In [85]:
import numpy as np

def hypercube(n):
    if not n:
        return np.zeros(1,int)
    n2 = 2**(n-1)
    A = np.identity(n2,int)
    B = hypercube(n-1)
    
    C = np.zeros((2**n,2**n),int)
    C[:n2,:n2],C[n2:,n2:], C[:n2,n2:],C[n2:,:n2] = B,B, A,A
    return C

for x in range(5):
    print(hypercube(x),'\n')
    

[0] 

[[0 1]
 [1 0]] 

[[0 1 1 0]
 [1 0 0 1]
 [1 0 0 1]
 [0 1 1 0]] 

[[0 1 1 0 1 0 0 0]
 [1 0 0 1 0 1 0 0]
 [1 0 0 1 0 0 1 0]
 [0 1 1 0 0 0 0 1]
 [1 0 0 0 0 1 1 0]
 [0 1 0 0 1 0 0 1]
 [0 0 1 0 1 0 0 1]
 [0 0 0 1 0 1 1 0]] 

[[0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0]
 [1 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0]
 [0 1 1 0 0 0 0 1 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 1 0 0 1 0 0 0 0 0 1 0 0]
 [0 0 1 0 1 0 0 1 0 0 0 0 0 0 1 0]
 [0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 1 0 0 1 0 1 0 0]
 [0 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0]
 [0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0]
 [0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 1]
 [0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0]] 



    4 = 000 -> 100 -> 110 -> 111 -> 011
    7 = 0000 -> 1000 -> 1100 -> 1110 -> 0110 -> 0111 -> 0011 -> 1011

Thinking about the maths, comments welcome:
The induced path is related to the max independent set (MIS).
Finding a MIS seems tractable for hypercubes. A Line: 1 point, a square: two points, a cube: four points, ... When you observe this, you'll notice that they inherit from each other:

    0
    00  ,11
    000 ,110 ,101 ,011 
    0000,1100,1010,0110,...
    
You can always find the new MIS elements as those that are not connected to the inherited MIS.

    Can the max induced path be found among the possible paths (PP) connecting the MIS?
    
    How can symmetry be used to reduce the branches of PP? 
    For example does the symmetry mean we only have to search 1 permutation of MIS elements?
    
    Can we use 2 non-overlapping MISes to aid in the choice of the path?

In [128]:
def hypercube(n):
    if not n:
        return np.zeros(1,int),np.identity(1,int)
    n2 = 2**(n-1)
    A = np.identity(n2,int)
    B,a_solution = hypercube(n-1)    
    C = np.zeros((2**n,2**n),int)
    C[:n2,:n2],C[n2:,n2:], C[:n2,n2:],C[n2:,:n2] = B,B, A,A
    for x in a_solution:
        C[:,x],C[x,:] = 0,0
    return C,a_solution

for x in range(6):
    print(hypercube(x),'\n')

(array([0]), [0]) 

(array([[0, 0],
       [0, 0]]), [0]) 

(array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 1, 0, 0]]), [0]) 

(array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0]]), [0]) 

(array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
 

In [125]:
D = np.identity(4) + np.flip(np.identity(4),0)
D[0,:],D[:,0] = 0,0
D

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

1-1
2-1/1.1
4-2/2.1
8-4/3.2
16-8/4.
32-16/

0-1-1-1
1-2-1.1-2-1
2-4-1.3-3-1
3-8-3.3(8-3-2)-5-2
4-16-5.6(16-5-4)-8-3
5-32-8.17(32-8-7)-14-6
6-64-14.37(64-14-13)-27-13
7-128-27.75(128-27-26)-51-24
8-256-51.155(256-51-50)-99-48


In [133]:
2**8


256